// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

type NewTodo struct {
	Text string `json:"text"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}
