// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

// User is an object representing the database table.
type User struct {
	ID        uint
	FirstName string
	LastName  string
}
